//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoUIApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgChartConnections
    {
        public int Id { get; set; }
        public Nullable<int> FromShapeId { get; set; }
        public Nullable<int> ToShapeId { get; set; }
        public string Text { get; set; }
        public Nullable<int> FromPointX { get; set; }
        public Nullable<int> FromPointY { get; set; }
        public Nullable<int> ToPointX { get; set; }
        public Nullable<int> ToPointY { get; set; }
    }
}
